/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AppsNibrasArabicRouteImport } from './routes/apps/nibras-arabic'
import { Route as AppsPdfRouteImport } from './routes/apps/pdf'
import { Route as AppsPlansRouteImport } from './routes/apps/plans'
import { Route as AppsDocsRouteImport } from './routes/apps/docs'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsNibrasArabicRoute = AppsNibrasArabicRouteImport.update({
  id: '/apps/nibras-arabic',
  path: '/apps/nibras-arabic',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsPdfRoute = AppsPdfRouteImport.update({
  id: '/apps/pdf',
  path: '/apps/pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsPlansRoute = AppsPlansRouteImport.update({
  id: '/apps/plans',
  path: '/apps/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsDocsRoute = AppsDocsRouteImport.update({
  id: '/apps/docs',
  path: '/apps/docs',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/apps/nibras-arabic': typeof AppsNibrasArabicRoute
  '/apps/pdf': typeof AppsPdfRoute
  '/apps/plans': typeof AppsPlansRoute
  '/apps/docs': typeof AppsDocsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/apps/nibras-arabic': typeof AppsNibrasArabicRoute
  '/apps/pdf': typeof AppsPdfRoute
  '/apps/plans': typeof AppsPlansRoute
  '/apps/docs': typeof AppsDocsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/apps/nibras-arabic': typeof AppsNibrasArabicRoute
  '/apps/pdf': typeof AppsPdfRoute
  '/apps/plans': typeof AppsPlansRoute
  '/apps/docs': typeof AppsDocsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/contact' | '/apps/nibras-arabic' | '/apps/pdf' | '/apps/plans' | '/apps/docs'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/contact' | '/apps/nibras-arabic' | '/apps/pdf' | '/apps/plans' | '/apps/docs'
  id: '__root__' | '/' | '/about' | '/contact' | '/apps/nibras-arabic' | '/apps/pdf' | '/apps/plans' | '/apps/docs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  AppsNibrasArabicRoute: typeof AppsNibrasArabicRoute
  AppsPdfRoute: typeof AppsPdfRoute
  AppsPlansRoute: typeof AppsPlansRoute
  AppsDocsRoute: typeof AppsDocsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/nibras-arabic': {
      id: '/apps/nibras-arabic'
      path: '/apps/nibras-arabic'
      fullPath: '/apps/nibras-arabic'
      preLoaderRoute: typeof AppsNibrasArabicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/pdf': {
      id: '/apps/pdf'
      path: '/apps/pdf'
      fullPath: '/apps/pdf'
      preLoaderRoute: typeof AppsPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/plans': {
      id: '/apps/plans'
      path: '/apps/plans'
      fullPath: '/apps/plans'
      preLoaderRoute: typeof AppsPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/docs': {
      id: '/apps/docs'
      path: '/apps/docs'
      fullPath: '/apps/docs'
      preLoaderRoute: typeof AppsDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  AppsNibrasArabicRoute: AppsNibrasArabicRoute,
  AppsPdfRoute: AppsPdfRoute,
  AppsPlansRoute: AppsPlansRoute,
  AppsDocsRoute: AppsDocsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
